spring:
  application:
    name: JsonMover


  datasource:
    url: jdbc:postgresql://localhost:5433/Test
    username: postgres
    password: Nartkala36


  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml


  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

logging:
  file:
    name: logs/application.log
  level:
    root: INFO
    org.springframework: INFO
    com.example: ERROR
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30


